apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
spec:
  orphanedResources:
    warn: true
  sourceNamespaces:
    - default
    - argocd
    - stirling-pdf
    - php-apache
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: "*"
      server: "*"
  sourceRepos:
    - "*"
---
apiVersion: v1
kind: Namespace
metadata:
  name: stirling-pdf
---
apiVersion: v1
kind: Namespace
metadata:
  name: php-apache
