apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stirling-pdf
  namespace: stirling-pdf
spec:
  project: default

  destination:
    name: in-cluster
    namespace: stirling-pdf

  sources:
    - repoURL: https://stirling-tools.github.io/Stirling-PDF-chart
      chart: stirling-pdf-chart
      targetRevision: "*"
      helm:
        ignoreMissingValueFiles: true
        valueFiles:
          - $values/apps/stirling-pdf/values.yaml
    - repoURL: https://github.com/mirza-src/cc-argocd-gitops.git
      ref: values
    # - repoURL: https://github.com/mirza-src/cc-argocd-gitops.git
    #   path: apps/stirling-pdf
    #   directory:
    #     recurse: false
    #     include: hpa.{yaml,yml,json}
