apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: stirling-pdf
  namespace: stirling-pdf
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stirling-pdf

  minReplicas: 1
  maxReplicas: 5

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
