replicaCount: 0 # Disable deployment due to resource constraints

resources:
  limits:
    cpu: 500m # Process will be slower but allow more pods to run in limited resources

# Lower CPU limits means container will take longer to start, adjust probes accordingly
probes:
  liveness:
    initialDelaySeconds: 60
    periodSeconds: 15
    failureThreshold: 10
  readiness:
    initialDelaySeconds: 60
    periodSeconds: 15
    failureThreshold: 10

fullnameOverride: stirling-pdf

ingress:
  enabled: true
  ingressClassName: nginx

  hosts:
    - name: stirling.mirzaesaaf.me
      path: /
      tls: true
      tlsSecret: stirling-pdf-tls

  annotations:
    cert-manager.io/cluster-issuer: letsencrypt

tolerations:
  - key: "kubernetes.azure.com/scalesetpriority"
    operator: "Equal"
    value: "spot"
    effect: "NoSchedule"
