dex:
  enabled: false # Disable Dex, we will be using local ArgoCD authentication

configs:
  params:
    server.insecure: "true" # Offload TLS termination to the ingress controller
    controller.diff.server.side: "true"
    application.namespaces: "*"
