apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: php-apache
  namespace: php-apache
spec:
  project: default

  destination:
    name: in-cluster
    namespace: php-apache

  sources:
    - repoURL: https://github.com/mirza-src/cc-argocd-gitops.git
      path: apps/php-apache
      directory:
        recurse: false
        # Disable deployment due to unavailability of amd64 nodes (image not available for arm64)
        exclude: "{app,hpa}.{yaml,yml,json}"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
