apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  namespace: php-apache
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: php-apache
  template:
    metadata:
      labels:
        app.kubernetes.io/name: php-apache
    spec:
      containers:
        - name: php-apache
          image: registry.k8s.io/hpa-example
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  labels:
    app.kubernetes.io/name: php-apache
spec:
  ports:
    - port: 80
  selector:
    app.kubernetes.io/name: php-apache
