apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  namespace: php-apache
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: php-apache
  template:
    metadata:
      labels:
        app.kubernetes.io/name: php-apache
    spec:
      containers:
        - name: php-apache
          image: registry.k8s.io/hpa-example
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  labels:
    app.kubernetes.io/name: php-apache
spec:
  ports:
    - port: 80
  selector:
    app.kubernetes.io/name: php-apache
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: php-apache
  namespace: php-apache
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  rules:
    - host: php-apache.mirzaesaaf.me
      http:
        paths:
          - backend:
              service:
                name: php-apache
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - php-apache.mirzaesaaf.me
      secretName: php-apache-tls
