apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: ingress
spec:
  project: infrastructure

  destination:
    name: in-cluster
    namespace: ingress

  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: "*"
      helm:
        ignoreMissingValueFiles: true
        valueFiles:
          - $values/infrastructure/cert-manager/values.yaml
    - repoURL: https://github.com/mirza-src/cc-argocd-gitops.git
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
