crds:
  enabled: true

podLabels:
  azure.workload.identity/use: "true"

extraObjects:
  - |
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: letsencrypt
    spec:
      acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        preferredChain: ISRG Root X1
        email: mirzaesaaf@outlook.com
        privateKeySecretRef:
          name: cert-manager-letsencrypt-issuer
        solvers:
          - dns01:
              azureDNS:
                subscriptionID: 9a3616bd-69cc-407c-b4c0-473e27174699
                resourceGroupName: rg-cc-project-ci
                managedIdentity:
                  clientID: 4391e608-c601-4305-9847-7df23fab6a7c
